### ISSUE TITLE
Paid training course addition

### ISSUE THREAD

**Issue by jksecurity** [secfigo/Awesome-Fuzzing#2]
Hello,

I'm not sure on how to create a pull request to add another training course. Last year I attended the Vuln-Dev Master Class from Exodus Intelligence. No further affiliation.

Link: https://blog.exodusintel.com/2016/05/18/exodus-intelligence-2016-training-course/

**Comment by secfigo** [comment]
Thanks for sharing your experience regarding the training. Will add it in the next iteration this week.

**Comment by jksecurity** [comment]
Cool.

In terms of tools, you could also add Grinder: https://github.com/stephenfewer/grinder

**Comment by secfigo** [comment]
Sure, consider it done :)

**Comment by secfigo** [comment]
I have updated the repo with your suggestion and have thanked you under contribution section.

Thanks.
