### ISSUE TITLE
MiniFuzz

### ISSUE THREAD

**Issue by biorpg** [secfigo/Awesome-Fuzzing#21]
The link for MiniFuzz is broken, as MS pulled the download.
But the wayback machine caught it:
[MiniFuzz](https://web.archive.org/web/20140512203517/http://download.microsoft.com/download/D/6/E/D6EDC908-A1D7-4790-AB0B-66A8B35CD931/MiniFuzzSetup.msi)

**Comment by secfigo** [comment]
Thanks @biorpg, will update the README
