### ISSUE TITLE
Network Protocol Fuzzers

### ISSUE THREAD

**Issue by dobin** [secfigo/Awesome-Fuzzing#33]
Cool list, very useful!

Some things about network protocol fuzzers, which i'm currently intersted in:

* I checked Nightmare, but i'm unable to see the network-fuzzing capabilities. Are you sure it can fuzz network things (imho it's more a distributed file fuzzer)?
* I'm developing FFW network fuzzer, maybe can add them? https://github.com/dobin/ffw
* Theres's also: 
  * https://github.com/denandz/fuzzotron
  * https://github.com/Cisco-Talos/mutiny-fuzzer

**Comment by secfigo** [comment]
@dobin Please feel free to raise a PR to add your fuzzer and others you mentioned above :)

**Comment by secfigo** [comment]
closing this as #34 is merged into the repo.
